### ISSUE TITLE
Is autorank up to date? Autorank 3.5.1

### ISSUE THREAD

**Issue by co2footprint** [Armarr/Autorank-2#204]
Hey. My server is running on 1.8.1 and I recently started using Autorank, it wokred flawelessly untill someone told me it stopped working. I restarted the server to see if that would fix it, sadly it didnt. Could you please help me.

Pastebin:

Server Log: http://pastebin.com/AwvRWxTnl
AdvancedConfig: http://pastebin.com/FR0i2Xax
Settings: http://pastebin.com/dKv2v0jp

**Comment by co2footprint** [comment]
@Staartvin

**Comment by Staartvin** [comment]
Could you reupload the server log? Any errors you're getting?

**Comment by co2footprint** [comment]
I fixed IT

**Comment by Staartvin** [comment]
You fixed the problem or the pastebin? I still cannot access the server log pastebin.
